/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteRouteImport } from './routes/index/route'
import { Route as AuthenticatedWorkoutRouteRouteImport } from './routes/_authenticated/workout/route'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRouteRoute = IndexRouteRouteImport.update({
  id: '/',
  path: '',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkoutRouteRoute =
  AuthenticatedWorkoutRouteRouteImport.update({
    id: '/workout',
    path: '/workout',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedRouteRouteWithChildren
  '/workout': typeof AuthenticatedWorkoutRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedRouteRouteWithChildren
  '/workout': typeof AuthenticatedWorkoutRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRouteRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/workout': typeof AuthenticatedWorkoutRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/workout'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/workout'
  id: '__root__' | '/' | '/_authenticated' | '/_authenticated/workout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRouteRoute: typeof IndexRouteRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workout': {
      id: '/_authenticated/workout'
      path: '/workout'
      fullPath: '/workout'
      preLoaderRoute: typeof AuthenticatedWorkoutRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedWorkoutRouteRoute: typeof AuthenticatedWorkoutRouteRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedWorkoutRouteRoute: AuthenticatedWorkoutRouteRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRouteRoute: IndexRouteRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
